library(tidyverse)

names <- c(
  "group1",
  "id",
  "bibliografiai_halmaz",
  "sorszam",
  "jel",
  "group2",
  "x_fazis_01",
  "x_fazis_01_esemeny",
  "x_fazis_01_eredmeny",
  "x_fazis_01_utalas",
  "x_fazis_01_megjegyzes",
  "x_fazis_01_ev",
  "x_fazis_2024",
  "x_fazis_2024_esemeny",
  "x_fazis_2024_eredmeny",
  "x_fazis_2024_utalas",
  "x_fazis_2024_megjegyzes",
  "x_fazis_2024_ev",
  "external_data",
  "hypothetic",
  "x_nyelvi_hungarikum",
  "x_teruleti_hungarikum",
  "x_szemelyi_hungarikum",
  "x_targyi_hungarikum",
  "x_besorolas_bibliografiai_hagyomany",
  "x_besorolas_adat",
  "x_besorolas_logikai",
  "bibliografiai_hivatkozas",
  "tetel_megjegyzes",
  "x_tetel_megjegyzes",
  "group3",
  "nyomtatasi_hely",
  "x_nyomtatasi_hely",
  "stat_geonames",
  "nyomtatasi_ev",
  "x_nyomtatasi_ev",
  "x_ido_evtized",
  "x_szerzo",
  "szerzo",
  "leiras",
  "nyomda_nyomdasz",
  "x_nyomda",
  "x_nyomdasz",
  "kollacio",
  "levelek_lapok",
  "x_pf",
  "x_lapok",
  "formatum",
  "x_formatum",
  "x_formatum_2",
  "x_oldal_iv",
  "x_peldany_iv2",
  "x_iv_peldany",
  "x_terjedelem",
  "x_formatum2",
  "oldal_per_iv",
  "ivszam",
  "konyvdiszek",
  "x_konyvdisz",
  "x_illusztracio",
  "x_inicale",
  "x_cimer",
  "x_hangjegy",
  "x_terkep",
  "x_rezmetszet",
  "x_szines",
  "x_tab",
  "x_kiadvany_variansA",
  "x_kiadvany_variansB",
  "x_kiadvany_variansC",
  "x_kiadvany_variansD",
  "x_kiadvany_variansE",
  "group4",
  "tartalom_meghatarozas",
  "x_vallas",
  "x_szovegforma",
  "x_kiadvanytipus",
  "x_mufajszint01",
  "x_mufajszint02",
  "x_mufajszint03",
  "x_mufajszint04",
  "facsimile",
  "x_nyelvek",
  "group5",
  "letezo_peldanyok",
  "x_letezo_peldanyok_szama",
  "x_letezo_peldanyok_szorodasa",
  "letezett_peldanyok",
  "x_letezett_peldanyok_szama",
  "x_letezett_peldanyok_szorodasa",
  "x_konyvtorteneti_peldanyok",
  "x_konyvtorteneti_peldanyok_szama",
  "group6",
  "x_peldanyszamadat_tudas_jellege",
  "x_celkozonseg_jellege",
  "x_celkozonseg_megjegyzes",
  "x_kiadott_peldanyszam_min",
  "x_kiadott_peldanyszam_max",
  "x_ivkiadvany_min",
  "x_ivkiadvany_max",
  "x_kiadott_peldanyszam_megjegyzes",
  "x_koltsegviselo",
  "x_finanszirozas_jellege",
  "x_patronus_jellege",
  "x_patronus",
  "x_patronus_tarsadalmi_helyzete",
  "x_tudashalmaz",
  "empty1",
  "empty2",
  "empty3"
)

types <- cols(
  `group1` = col_character(),
  `id` = col_character(),
  `bibliografiai_halmaz` = col_character(),
  `sorszam` = col_double(),
  `jel` = col_character(),
  `group2` = col_character(),
  `x_fazis_01` = col_character(),
  `x_fazis_01_esemeny` = col_character(),
  `x_fazis_01_eredmeny` = col_character(),
  `x_fazis_01_utalas` = col_character(),
  `x_fazis_01_megjegyzes` = col_character(),
  `x_fazis_01_ev` = col_character(),
  `x_fazis_2024` = col_character(),
  `x_fazis_2024_esemeny` = col_character(),
  `x_fazis_2024_eredmeny` = col_character(),
  `x_fazis_2024_utalas` = col_character(),
  `x_fazis_2024_megjegyzes` = col_character(),
  `x_fazis_2024_ev` = col_character(),
  `external_data` = col_character(),
  `hypothetic` = col_character(),
  `x_nyelvi_hungarikum` = col_character(),
  `x_teruleti_hungarikum` = col_character(),
  `x_szemelyi_hungarikum` = col_character(),
  `x_targyi_hungarikum` = col_character(),
  `x_besorolas_bibliografiai_hagyomany` = col_character(),
  `x_besorolas_adat` = col_character(),
  `x_besorolas_logikai` = col_character(),
  `bibliografiai_hivatkozas` = col_character(),
  `tetel_megjegyzes` = col_character(),
  `x_tetel_megjegyzes` = col_character(),
  `group3` = col_character(),
  `nyomtatasi_hely` = col_character(),
  `x_nyomtatasi_hely` = col_character(),
  `stat_geonames` = col_character(),
  `nyomtatasi_ev` = col_character(),
  `x_nyomtatasi_ev` = col_double(),
  `x_ido_evtized` = col_character(),
  `x_szerzo` = col_character(),
  `szerzo` = col_character(),
  `leiras` = col_character(),
  `nyomda_nyomdasz` = col_character(),
  `x_nyomda` = col_character(),
  `x_nyomdasz` = col_character(),
  `kollacio` = col_character(),
  `levelek_lapok` = col_character(),
  `x_pf` = col_character(),
  `x_lapok` = col_double(),
  `formatum` = col_character(),
  `x_formatum` = col_double(),
  `x_formatum_2` = col_double(),
  `x_oldal_iv` = col_character(),
  `x_peldany_iv2` = col_character(),
  `x_iv_peldany` = col_character(),
  `x_terjedelem` = col_double(),
  `x_formatum2` = col_double(),
  `oldal_per_iv` = col_double(),
  `ivszam` = col_character(),
  `konyvdiszek` = col_character(),
  `x_konyvdisz` = col_character(),
  `x_illusztracio` = col_character(),
  `x_inicale` = col_character(),
  `x_cimer` = col_character(),
  `x_hangjegy` = col_character(),
  `x_terkep` = col_character(),
  `x_rezmetszet` = col_character(),
  `x_szines` = col_character(),
  `x_tab` = col_character(),
  `x_kiadvany_variansA` = col_character(),
  `x_kiadvany_variansB` = col_character(),
  `x_kiadvany_variansC` = col_character(),
  `x_kiadvany_variansD` = col_character(),
  `x_kiadvany_variansE` = col_character(),
  `group4` = col_character(),
  `tartalom_meghatarozas` = col_character(),
  `x_vallas` = col_character(),
  `x_szovegforma` = col_character(),
  `x_kiadvanytipus` = col_character(),
  `x_mufajszint01` = col_character(),
  `x_mufajszint02` = col_character(),
  `x_mufajszint03` = col_character(),
  `x_mufajszint04` = col_character(),
  `facsimile` = col_character(),
  `x_nyelvek` = col_character(),
  `group5` = col_character(),
  `letezo_peldanyok` = col_character(),
  `x_letezo_peldanyok_szama` = col_double(),
  `x_letezo_peldanyok_szorodasa` = col_character(),
  `letezett_peldanyok` = col_character(),
  `x_letezett_peldanyok_szama` = col_double(),
  `x_letezett_peldanyok_szorodasa` = col_character(),
  `x_konyvtorteneti_peldanyok` = col_character(),
  `x_konyvtorteneti_peldanyok_szama` = col_character(),
  `group6` = col_character(),
  `x_peldanyszamadat_tudas_jellege` = col_character(),
  `x_celkozonseg_jellege` = col_character(),
  `x_celkozonseg_megjegyzes` = col_character(),
  `x_kiadott_peldanyszam_min` = col_double(),
  `x_kiadott_peldanyszam_max` = col_double(),
  `x_ivkiadvany_min` = col_character(),
  `x_ivkiadvany_max` = col_character(),
  `x_kiadott_peldanyszam_megjegyzes` = col_character(),
  `x_koltsegviselo` = col_character(),
  `x_finanszirozas_jellege` = col_character(),
  `x_patronus_jellege` = col_character(),
  `x_patronus` = col_character(),
  `x_patronus_tarsadalmi_helyzete` = col_character(),
  `x_tudashalmaz` = col_character(),
  `empty1` = col_character(),
  `empty2` = col_character(),
  `empty3` = col_character()
)

names[99]
names[100]

# df <- read_csv('data_raw/v02/RMNYStat-data_v02_20240826 - RMNYStat-v02.csv')
# names(df)
# df %>% group_by(`Csoport-Tétel adatok`) %>% count()

df <- read_csv('data_raw/v02/RMNYStat-data_v02_20240826 - RMNYStat-v02.csv',
               skip = 1,
               col_names = names,
               col_types = types)

df <- df %>% 
  select(-c(group1, group2, group3, group4, group5, group6,
            empty1, empty2, empty3)) %>% 
  mutate(
    ivszam = as.numeric(str_replace(ivszam, ",", ".")),
    x_ivkiadvany_min = as.numeric(str_replace(x_ivkiadvany_min, ",", ".")),
    x_ivkiadvany_max = as.numeric(str_replace(x_ivkiadvany_max, ",", ".")),
    external_data = ifelse(is.na(external_data), FALSE, ifelse(external_data == "1", TRUE, FALSE)),
    hypothetic = ifelse(is.na(hypothetic), FALSE, ifelse(hypothetic == "x", TRUE, FALSE)),
    x_nyelvi_hungarikum = ifelse(is.na(x_nyelvi_hungarikum), FALSE, ifelse(x_nyelvi_hungarikum == "x", TRUE, FALSE)),
    x_teruleti_hungarikum = ifelse(is.na(x_teruleti_hungarikum), FALSE, ifelse(x_teruleti_hungarikum == "x", TRUE, FALSE)),
    x_szemelyi_hungarikum = ifelse(is.na(x_szemelyi_hungarikum), FALSE, ifelse(x_szemelyi_hungarikum == "x", TRUE, FALSE)),
    x_targyi_hungarikum = ifelse(is.na(x_targyi_hungarikum), FALSE, ifelse(x_targyi_hungarikum == "x", TRUE, FALSE)),
    x_besorolas_bibliografiai_hagyomany = ifelse(is.na(x_besorolas_bibliografiai_hagyomany), FALSE, ifelse(x_besorolas_bibliografiai_hagyomany == "x", TRUE, FALSE)),
    x_besorolas_adat = ifelse(is.na(x_besorolas_adat), FALSE, ifelse(x_besorolas_adat == "x", TRUE, FALSE)),
    x_besorolas_logikai = ifelse(is.na(x_besorolas_logikai), FALSE, ifelse(x_besorolas_logikai == "x", TRUE, FALSE)),
    x_konyvdisz = ifelse(is.na(x_konyvdisz), FALSE, ifelse(x_konyvdisz == "x", TRUE, FALSE)),
    x_illusztracio = ifelse(is.na(x_illusztracio), FALSE, ifelse(x_illusztracio == "x", TRUE, FALSE)),
    x_inicale = ifelse(is.na(x_inicale), FALSE, ifelse(x_inicale == "x", TRUE, FALSE)),
    x_cimer = ifelse(is.na(x_cimer), FALSE, ifelse(x_cimer == "x", TRUE, FALSE)),
    x_hangjegy = ifelse(is.na(x_hangjegy), FALSE, ifelse(x_hangjegy == "x", TRUE, FALSE)),
    x_terkep = ifelse(is.na(x_terkep), FALSE, ifelse(x_terkep == "x", TRUE, FALSE)),
    x_rezmetszet = ifelse(is.na(x_rezmetszet), FALSE, ifelse(x_rezmetszet == "x", TRUE, FALSE)),
    x_szines = ifelse(is.na(x_szines), FALSE, ifelse(x_szines == "x", TRUE, FALSE)),
    x_tab = ifelse(is.na(x_tab), FALSE, ifelse(x_tab == "x", TRUE, FALSE)),
    x_kiadvany_variansA = ifelse(is.na(x_kiadvany_variansA), FALSE, ifelse(x_kiadvany_variansA == "var-A", TRUE, FALSE)),
    x_kiadvany_variansB = ifelse(is.na(x_kiadvany_variansB), FALSE, ifelse(x_kiadvany_variansB == "var-B", TRUE, FALSE)),
    x_kiadvany_variansC = ifelse(is.na(x_kiadvany_variansC), FALSE, ifelse(x_kiadvany_variansC == "var-C", TRUE, FALSE)),
    x_kiadvany_variansD = ifelse(is.na(x_kiadvany_variansD), FALSE, ifelse(x_kiadvany_variansD == "var-D", TRUE, FALSE)),
    x_kiadvany_variansE = ifelse(is.na(x_kiadvany_variansE), FALSE, ifelse(x_kiadvany_variansE == "var-E", TRUE, FALSE)),
  )

write_tsv(df, 'data_raw/rmny-v02.tsv', na = "")
write_tsv(df, 'shiny/rmny/data/rmny-v02.tsv', na = "")

write_rds(df, 'data_raw/rmny-v02.rds')
write_rds(df, 'shiny/rmny/data/rmny-v02.rds')
