library(tidyverse)

names <- c(
  "id",
  "bibliografiai_halmaz",
  "sorszam",
  "S",
  "external_data",
  "hypothetic",
  "x_nyelvi_hungarikum",
  "x_teruleti_hungarikum",
  "x_szemelyi_hungarikum",
  "x_targyi_hungarikum",
  "nyomtatasi_hely",
  "x_nyomtatasi_hely",
  "stat_geonames",
  "nyomtatasi_ev",
  "x_nyomtatasi_ev",
  "x_ido_evtized",
  "x_szerzo",
  "szerzo",
  "leiras",
  "nyomda_nyomdasz",
  "x_nyomda",
  "x_nyomdasz",
  "kollacio",
  "levelek_lapok",
  "x_pf",
  "x_lapok",
  "formatum",
  "x_formatum",
  "x_formatum_2",
  "x_oldal_iv",
  "x_iv_peldany",
  "konyvdiszek",
  "x_konyvdisz",
  "x_illusztracio",
  "x_inicale",
  "x_cimer",
  "x_hangjegy",
  "x_terkep",
  "x_rezmetszet",
  "x_szines",
  "x_tab",
  "bibliografiai_hivatkozas",
  "tartalom_meghatarozas",
  "x_vallas",
  "x_szovegforma",
  "x_kiadvanytipus",
  "x_mufajszint01",
  "x_mufajszint02",
  "x_mufajszint03",
  "x_mufajszint04",
  "facsimile",
  "x_nyelvek",
  "letezo_peldanyok",
  "x_letezo_peldanyok_szama",
  "x_letezo_peldanyok_szorodasa",
  "letezett_peldanyok",
  "x_letezett_peldanyok_szama",
  "x_letezett_peldanyok_szorodasa",
  "x_tudashalmaz",
  "tetel_megjegyzes",
  "stat_tetel_megjegyzes",
  "x_terjedelem",
  "x_formatum2",
  "oldal_per_iv",
  "ivszam",
  "x_kiadott_peldanyszam_min",
  "x_kiadott_peldanyszam_max",
  "x_kiadott_peldanyszam_megjegyzes"
)
types <- cols(
  `id` = col_character(),
  `bibliografiai_halmaz` = col_character(),
  `sorszam` = col_double(),
  `S` = col_character(),
  external_data = col_double(),
  hypothetic = col_double(),
  `x_nyelvi_hungarikum` = col_character(),
  `x_teruleti_hungarikum` = col_character(),
  `x_szemelyi_hungarikum` = col_character(),
  `x_targyi_hungarikum` = col_logical(),
  `nyomtatasi_hely` = col_character(),
  `x_nyomtatasi_hely` = col_character(),
  `stat_geonames` = col_character(),
  `nyomtatasi_ev` = col_character(),
  `x_nyomtatasi_ev` = col_double(),
  `x_ido_evtized` = col_character(),
  `x_szerzo` = col_character(),
  `szerzo` = col_character(),
  `leiras` = col_character(),
  `nyomda_nyomdasz` = col_character(),
  `x_nyomda` = col_character(),
  `x_nyomdasz` = col_character(),
  `kollacio` = col_character(),
  `levelek_lapok` = col_character(),
  `x_pf` = col_character(),
  `x_lapok` = col_double(),
  `formatum` = col_character(),
  `x_formatum` = col_double(),
  `x_formatum_2` = col_double(),
  `x_oldal_iv` = col_double(),
  `x_iv_peldany` = col_character(),
  `konyvdiszek` = col_character(),
  `x_konyvdisz` = col_character(),
  `x_illusztracio` = col_character(),
  `x_inicale` = col_character(),
  `x_cimer` = col_character(),
  `x_hangjegy` = col_character(),
  `x_terkep` = col_character(),
  `x_rezmetszet` = col_character(),
  `x_szines` = col_character(),
  `x_tab` = col_character(),
  `bibliografiai_hivatkozas` = col_character(),
  `tartalom_meghatarozas` = col_character(),
  `x_vallas` = col_character(),
  `x_szovegforma` = col_character(),
  `x_kiadvanytipus` = col_character(),
  `x_mufajszint01` = col_character(),
  `x_mufajszint02` = col_character(),
  `x_mufajszint03` = col_character(),
  `x_mufajszint04` = col_character(),
  `facsimile` = col_character(),
  `x_nyelvek` = col_character(),
  `letezo_peldanyok` = col_character(),
  `x_letezo_peldanyok_szama` = col_double(),
  `x_letezo_peldanyok_szorodasa` = col_character(),
  `letezett_peldanyok` = col_character(),
  `x_letezett_peldanyok_szama` = col_double(),
  `x_letezett_peldanyok_szorodasa` = col_character(),
  `x_tudashalmaz` = col_character(),
  `tetel_megjegyzes` = col_character(),
  `stat_tetel_megjegyzes` = col_character(),
  `x_terjedelem` = col_double(),
  `x_formatum2` = col_double(),
  oldal_per_iv = col_double(),
  ivszam = col_character(),
  `x_kiadott_peldanyszam_min` = col_double(),
  `x_kiadott_peldanyszam_max` = col_double(),
  `x_kiadott_peldanyszam_megjegyzes` = col_character()
)
df <- read_tsv('data_raw/RMNYStat-v04 - RMNYStat-Egyesített tábla.tsv',
               skip = 1,
               col_names = names,
               col_types = types)

df <- df %>% 
  mutate(
    ivszam = as.numeric(str_replace(ivszam, ",", ".")),
    x_nyelvi_hungarikum = ifelse(is.na(x_nyelvi_hungarikum), NA, ifelse(x_nyelvi_hungarikum == "x", TRUE, FALSE)),
    x_teruleti_hungarikum = ifelse(is.na(x_teruleti_hungarikum), NA, ifelse(x_teruleti_hungarikum == "x", TRUE, FALSE)),
    x_szemelyi_hungarikum = ifelse(is.na(x_szemelyi_hungarikum), NA, ifelse(x_szemelyi_hungarikum == "x", TRUE, FALSE)),
    x_targyi_hungarikum = ifelse(is.na(x_targyi_hungarikum), NA, ifelse(x_targyi_hungarikum == "x", TRUE, FALSE)),
  )


write_tsv(df, 'data_raw/rmny-1-5.tsv', na = "")
write_tsv(df, 'shiny/rmny/data/rmny-1-5.tsv', na = "")

write_rds(df, 'data_raw/rmny-1-5.rds')
write_rds(df, 'shiny/rmny/data/rmny-1-5.rds')
